### ISSUE TITLE
pip editable install doesn't write `__version__.py`

### ISSUE THREAD

**Issue by beckermr** [lsst/rubin_scheduler#50]
It turns out a pip editable install via 

```
pip install --no-deps --no-build-isolation -e .       
```

doesn't write the proper `__version__.py` file. 

This is a symptom of the general state of flux / brokenness in python packaging ecosystem at the moment. 

I suspect moving to setuptools_scm version 7 or later and dropping the older git archive package will help. 

OTOH I honestly have no idea why or how or what is happening.

**Comment by timj** [comment]
Or using `importlib.metadata` to get the version dynamically in `__init__.py` rather than trying to write a `__version__.py` file?

**Comment by beckermr** [comment]
The repo also appears to be missing these files:

https://github.com/regro/cf-scripts/blob/master/.git_archival.txt
https://github.com/regro/cf-scripts/blob/master/.gitattributes

which are needed for git versioning in archives.

**Comment by beckermr** [comment]
Ahhhh it is setuptools-scm 8 in my env. 🤦

**Comment by beckermr** [comment]
The archive files above are still needed though.

**Comment by beckermr** [comment]
closing and will make a new issue
